site_name: Reestimativa
site_url: mariaefod.github.io/repositorio-pessoal/
theme:
  name: zensical
  palette:
    scheme: slate
    primary: teal
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - blog
